FROM golang:alpine

ENV GIN_MODE=release
RUN apk add --no-cache git

WORKDIR /app

COPY go.mod .
COPY go.sum .   

RUN go mod download

COPY . .

# Build the Go app
RUN go build -o ./out/gobin ./console/console.go

ENTRYPOINT ["./out/gobin"]