FROM golang:alpine

ENV GIN_MODE=release
ENV PORT=5000

RUN apk add --no-cache git

WORKDIR /app

COPY go.mod .
COPY go.sum .   

RUN go mod download

COPY . .

# Build the Go app
RUN go build -o ./out/gobin ./ibanService/ibanService.go

EXPOSE $PORT

CMD ["./out/gobin"]